### ISSUE TITLE
Oh no! We couldn't connect to HTTP Toolkit. Is it running, and connected to the same network as this device?

### ISSUE THREAD

**Issue by thorbn** [httptoolkit/httptoolkit-android#11]
Hello. Whenever I launch the Android app and try connecting it to my Windows machine (which is on the same network) I get the error stated in the title. I haven't found myself having any issues with other apps. I have a Xiaomi Note 11 running Android version 11 RKQ1.200826.002 and MIUI-Version MIUI Global 12.5.7 Stable 12.5.7.0(RKFEUXM). My phone isn't rooted.
If you guys need any more info from me I would be happy to provide it.

**Comment by thorbn** [comment]
Thanks for your help. I deactivated all firewalls that could be causing this and now it's working!

**Comment by pimterry** [comment]
Excellent! I'll close this now, glad that sorted it for you :+1:
