### ISSUE TITLE
Waydroid support

### ISSUE THREAD

**Issue by junyu33** [httptoolkit/httptoolkit-android#13]
Because Waydroid cannot use camera or Wi-Fi. Is there any plan to add support of scanning the QR-code by image file?

**Comment by pimterry** [comment]
Can Waydroid use ADB? That's usually preferable to QR codes in lots of ways, especially because it doesn't require a camera.

**Comment by junyu33** [comment]
Oh, I forgot Waydroid can use ADB shell besides its own shell. It works like a charm. Thanks.
