### ISSUE TITLE
Certificate rejected for connection to name_of_server.org

### ISSUE THREAD

**Issue by rotekii** [httptoolkit/httptoolkit-android#23]
I'm trying to intercept the traffic of this specific application but this is what prompted:
```Certificate rejected for connection to name_of_server.org```
I tried with another application and it works perfectly.
How can this issue be solved?

**Comment by pimterry** [comment]
Hi @rotekii that message means for some reason the client is rejecting HTTP Toolkit's certificate. Assuming you're have system certificates injected (not just user certificates) then this normally means there's an issue related to certificate pinning. See this article for more info: https://httptoolkit.com/blog/frida-certificate-pinning/
