### ISSUE TITLE
Where can I find the certificate that got installed as a system certificate?

### ISSUE THREAD

**Issue by endrits079** [httptoolkit/httptoolkit-android#27]
I am using an emulator and it successfully installed the certificate, although it wasn't enough so I proceeded with using Frida to disable certificate pinning, but I need to get the PEM key and I cannot find the certificate file

**Comment by pimterry** [comment]
Hi @endrits079. The certificate is generated on your computer, it's just copied to the device.

You can export it directly on your computer from the Anything option on the Intercept page, or you can download it through the proxy by visiting `amiusing.httptoolkit.tech/certificate` while connected to HTTP Toolkit.
