### ISSUE TITLE
httptookit on emulator

### ISSUE THREAD

**Issue by MRezaNasirloo** [httptoolkit/httptoolkit-android#5]
Hi, 

I noticed the ADB option is disabled; I couldn’t find why or how to fix it.

Thanks

<img width="210" alt="Screen Shot 2021-09-13 at 4 56 10 PM" src="https://user-images.githubusercontent.com/7994739/133083750-dfea1406-4613-4b91-8b04-896c6b70ccff.png">

**Comment by pimterry** [comment]
Hi @MRezaNasirloo, this generally means that your device isn't properly connected to ADB.

If you run `adb devices`, what does it show?

**Comment by shirshak55** [comment]
@pimterry Actually he might have got this issue due to ipv6.

There is one library something called ADB toolkit where I had to explicitly pass host 127.0.0.1 otherwise it would use ipv6 and ADB option is faded in HTTP toolkit :p

But it happened to me only when I built the app in the HTTP toolkit server. When I download an HTTP toolkit from a website and use that one it doesn't show an error.

Maybe we should add one option to the menu bar which shows logs ( I think if we open via shortcuts those logs are lost)?

Also I think this issue can be safely closed :)

**Comment by pimterry** [comment]
> Maybe we should add one option to the menu bar which shows logs ( I think if we open via shortcuts those logs are lost)?

I don't know about the menu bar, but I have been thinking we should start saving all console output to a log somewhere, so we can check it more easily for debugging.

Want to take a look at that? The first step would be to just pipe the server output [here](https://github.com/httptoolkit/httptoolkit-desktop/blob/248db686bd6c4f197ef7bd128de24c6eee766b40/src/index.ts#L352-L356) to a sensible log file path somewhere.

That would immediately be super useful. In future I'd love to get the output from the desktop shell too and the browser console output as well all in one place. Even just server output would be really helpful though, that's where most of the complicated invisible issues tend to live. Feel free to open a separate issue if you want to discuss this more, or if you have some time to look into it yourself.

> There is one library something called ADB toolkit where I had to explicitly pass host 127.0.0.1 otherwise it would use ipv6 and ADB option is faded in HTTP toolkit :p

Ah, wait you mean [this issue](https://github.com/DeviceFarmer/adbkit/pull/214) in adbkit that I fixed just last month? :smiley: That would break things if you were using Node 17 for development, which you might be? The version of Node used in the HTTP Toolkit distributable is v14 so this wouldn't affect anybody using the official builds, which fits what you're describing!

> Also I think this issue can be safely closed :)

Agreed, I'll close it now. Happy to investigate further if you can share any more info @MRezaNasirloo, but my best guess is that this is probably an ADB setup problem somewhere.
