### ISSUE TITLE
可以做到完全本地一个应用运行吗？即APP拿到流量直接本地转发到原始地址去，不经过任何服务器

### ISSUE THREAD

**Issue by yuanyuanjing** [httptoolkit/httptoolkit-android#7]

**Comment by pimterry** [comment]
Hi @yuanyuanjing! I'm sorry but I don't speak chinese. From Google Translate, I think your message means:

> Is it possible to run an application entirely locally? That is, the APP receives the traffic and forwards it to the original address directly, without passing through any server 

The HTTP Toolkit app does run locally on your computer. Internet connectivity is used for application installation & updates, error reporting, and paid account management, but it's not used for traffic interception at all or other application features.

Your HTTP traffic is never sent to HTTP Toolkit's servers.

What happens instead is that all HTTP traffic goes from the client application (on your computer or phone) to the HTTP Toolkit app (on your computer), and then on to the original destination (the target server, wherever that is).

Does that answer your question?

**Comment by yuanyuanjing** [comment]
是的。我的意思是只想在设备上完成这些工作。你的意思是如果只想通过一台Android设备完成流量的转发是需要大量的工作的事情，个人想完成它不是很现实吗？

**Comment by pimterry** [comment]
No, that's not something HTTP Toolkit can do. It is technically possible, but it's a very different approach, and it would require rebuilding most of HTTP Toolkit's features from scratch. Right now, the mobile app doesn't understand anything about HTTP or TLS at all.

I'm going to close this issue - this isn't something that HTTP Toolkit can help with, but of course you're welcome to use the open source components to build this for yourself if you'd like, or you can look at other Android apps that might work this way already, I don't know.
